#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Using a for loop to display "Best School" 10 times
counter=0
until [ $counter -eq 10 ]
do
  echo "Best School"
  counter=$((counter+1))
done
