#!/bin/bash
chown --from=File Edit Options Buffers Tools Help
#!/bin/bash
chown --from= betty hello



















-UUU:**--F1  102-if_only    All L2     (Fundamental) --------------------------- betty hello