#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Using a for until to display "Best School" 10 times
count=0

until [ $count -ge 10 ]; do
    echo "Best School"
    ((count++))
done
